'use strict';
module.exports = function (app) {
  const trips = require('../controllers/tripController');
  const authController = require('../controllers/authController');

  /**
   * @swagger
   * components:
   *  schemas:
   *    Trip:
   *      type: object
   *      properties:
   *        managerId:
   *          type: string
   *          description: The manager of the trip.
   *        ticker:
   *          type: string
   *          description: The ticker of the trip. Autogenerated.
   *        title:
   *          type: string
   *          description: The title of the trip.
   *        description:
   *          type: string
   *          description: The description of the trip.
   *        price:
   *          type: number
   *          description: The price of the trip. Autogenerated based in stages prices.
   *        requirements:
   *          type: array
   *          items:
   *            type: string
   *          description: The requirements of the trip.
   *        stages:
   *          type: array
   *          items:
   *            type: string
   *          description: The stages of the trip.
   *        startDate:
   *          type: date
   *          description: The start date of the trip.
   *        endDate:
   *          type: date
   *          description: The end date of the trip.
   *        files:
   *          type: array
   *          items:
   *            type: string
   *            format: binary
   *          description: Pictures of the trip.
   *        publication_date:
   *          type: date
   *          description: The publication date of the trip.
   *        canceled:
   *          type: boolean
   *          description: if the trip has been canceled.
   *        cancelReason:
   *          type: String
   *          description: if the trip has been canceled, it must have a reason.
   *
   *      required:
   *        - managerId
   *        - title
   *        - description
   *        - requirements
   *        - stages
   *        - startDate
   *        - endDate
   *
   *      example:
   *        managerId: 6218eca775428925392c633f
   *        title: Pirineo Aragones.
   *        description: Discover this beautiful place.
   *        requirements: ['Legal age.', 'Sun glases.']
   *        stages: [{'title': 'Zone 1 of Pirineo.', 'description': 'a description', 'price': 10}, {'title': 'Zone 2 of Pirineo.', 'description': 'a description', 'price': 10}]
   *        startDate: "2023-02-20T19:45:02.792Z"
   *        endDate: "2024-01-30T12:24:49.594Z"
   *
   *    Stage:
   *      type: object
   *      properties:
   *        title:
   *          type: string
   *          description: The title of the stage.
   *        description:
   *          type: string
   *          description: The description of the stage.
   *        price:
   *          type: number
   *          description: The price of the stage.
   *
   *      required:
   *        - title
   *        - description
   *        - price
   *
   *      example:
   *        title: Zone 1 of Pirineo
   *        description: More things about zone 1 of Pirineo
   *        price: 10
   */

  app.route('/v1/trips')

  /**
  * @swagger
  * /v1/trips:
  *    get:
  *      summary: Returns all trips.
  *      tags: [Trip]
  *      parameters:
  *        - in: query
  *          name: keyword
  *          schema:
  *            type: string
  *          required: false
  *          description: Single key word to filter trips by ticker, title, or description.
  *      responses:
  *        200:
  *          description: trips successfully retrieved.
  *          content:
  *            application/json:
  *              schema:
  *                type: array
  *                items:
  *                  $ref: '#/components/schemas/Trip'
  *        422:
  *          description: Invalid parameter.
  *        500:
  *          description: Error trying to get all trips.
  */
    .get(trips.list_all_trips)

  /**
   * @swagger
   * /v1/trips:
   *    post:
   *      summary: Create a new trip
   *      tags: [Trip]
   *      requestBody:
   *        required: true
   *        content:
   *          application/json:
   *            schema:
   *              type: object
   *              $ref: '#/components/schemas/Trip'
   *      responses:
   *        201:
   *          description: Trip created.
   *        400:
   *          description: Error trying to create the trip. Bad Request.
   *        401:
   *          description: Unauthorized.
   *        403:
   *          description: You don't have right role to carry out this operation. Only managers can create trips.
   *        500:
   *          description: Error trying to create the trip.
   *      security:
   *        - ApiKeyAuth: []
   */
    .post(
      authController.verifyAuthenticadedActor(['MANAGER']),
      trips.create_a_trip
    );

  app.route('/v1/trips/:tripId')

    /**
     * @swagger
     * /v1/trips/{tripId}:
     *    get:
     *      summary: Return a trip.
     *      tags: [Trip]
     *      parameters:
     *        - in: path
     *          name: tripId
     *          schema:
     *            type: string
     *          required: true
     *          description: trip id.
     *      responses:
     *        200:
     *          description: Trip successfully retrieved.
     *          content:
     *            application/json:
     *              schema:
     *                type: object
     *                $ref: '#/components/schemas/trip'
     *        404:
     *          description: trip not found.
     *        500:
     *          description: Error trying to get the trip.
     */
    .get(trips.read_a_trip)

  /**
     * @swagger
     * /v1/trips/{tripId}:
     *    put:
     *      summary: Update a trip.
     *      tags: [Trip]
     *      parameters:
     *        - in: path
     *          name: tripId
     *          schema:
     *            type: string
     *          required: true
     *          description: Trip id.
     *      requestBody:
     *        required: true
     *        content:
     *          application/json:
     *            schema:
     *              type: object
     *              $ref: '#/components/schemas/Trip'
     *      responses:
     *        200:
     *          description: Trip successfully updated.
     *          content:
     *            application/json:
     *              schema:
     *                type: object
     *                $ref: '#/components/schemas/Trip'
     *        403:
     *          description: You don't have right role to carry out this operation. Only a manager can update it.
     *        404:
     *          description: Trip not found.
     *        500:
     *          description: Error trying to update the trip.
     */
    .put(
      authController.verifyAuthenticadedActor(['MANAGER']),
      authController.verifyAuthenticatedActorCanAccessParameterTrip(),
      authController.verifyTripCanBeModifiedOrDeleted(),
      trips.update_a_trip
    )

    /**
     * @swagger
     * /v1/trips/{tripId}:
     *    delete:
     *      summary: Delete a trip.
     *      tags: [Trip]
     *      parameters:
     *        - in: path
     *          name: tripId
     *          schema:
     *            type: string
     *          required: true
     *          description: Trip id.
     *      responses:
     *        200:
     *          description: Trip successfully deleted.
     *          content:
     *            application/json:
     *              schema:
     *                type: object
     *                $ref: '#/components/schemas/Trip'
     *        403:
     *          description: You don't have right role to carry out this operation. Only a manager can delete it.
     *        404:
     *          description: Trip not found.
     *        500:
     *          description: Error trying to delete the trip.
     */
    .delete(
      authController.verifyAuthenticadedActor(['MANAGER']),
      authController.verifyAuthenticatedActorCanAccessParameterTrip(),
      authController.verifyTripCanBeModifiedOrDeleted(),
      trips.delete_a_trip
    );

  app.route('/v1/trips/:tripId/cancel')

  /**
       * @swagger
       * /v1/trips/{tripId}/cancel:
       *    patch:
       *      summary: Cancel a trip.
       *      tags: [Trip]
       *      parameters:
       *        - in: path
       *          name: tripId
       *          schema:
       *            type: string
       *          required: true
       *          description: key.
       *      responses:
       *        200:
       *          description: trips successfully calceled.
       *          content:
       *            application/json:
       *              schema:
       *                type: object
       *                $ref: '#/components/schemas/Trip'
       *        403:
       *          description: You don't have right role to carry out this operation.
       *        404:
       *          description: trip not found.
       *        500:
       *          description: Error trying to get the trip.
       */
    .patch(trips.cancel_a_trip);

  app.route('/v1/trips/:tripId/publish')

    /**
     * @swagger
     * /v1/trips/{tripId}/publish:
     *    patch:
     *      summary: Cancel a trip.
     *      tags: [Trip]
     *      parameters:
     *        - in: path
     *          name: trip Id
     *          schema:
     *            type: string
     *          required: true
     *          description: key.
     *      responses:
     *        200:
     *          description: trips successfully published.
     *          content:
     *            application/json:
     *              schema:
     *                type: object
     *                $ref: '#/components/schemas/Trip'
     *        403:
     *          description: You don't have right role to carry out this operation.
     *        404:
     *          description: trip not found.
     *        500:
     *          description: Error trying to get the trip.
     */
    .patch(trips.publish_a_trip);

  app.route('/v1/trips/:tripId/stages')

    /**
     * @swagger
     * /v1/stages:
     *    get:
     *      summary: Returns all stages.
     *      tags: [Stage]
     *      responses:
     *        200:
     *          description: stages successfully retrieved.
     *          content:
     *            application/json:
     *              schema:
     *                type: array
     *                items:
     *                  $ref: '#/components/schemas/Stage'
     *        500:
     *          description: Error trying to get all stages.
     */
    .get(trips.list_all_stages)

    /**
     * @swagger
     * /v1/stages:
     *    post:
     *      summary: Create a new stage
     *      tags: [Stage]
     *      requestBody:
     *        required: true
     *        content:
     *          application/json:
     *            schema:
     *              type: object
     *              $ref: '#/components/schemas/Stage'
     *      responses:
     *        201:
     *          description: Stage created.
     *        400:
     *          description: Error trying to create the Stage. Bad Request.
     *        403:
     *          description: You don't have right role to carry out this operation. Only managers can create stages.
     *        500:
     *          description: Error trying to create the Stage.
     */
    .post(trips.create_a_stage);

  app.route('/v1/stages/:stageId')

    /**
     * @swagger
     * /v1/stages/{stageId}:
     *    get:
     *      summary: Return a stage.
     *      tags: [Stage]
     *      parameters:
     *        - in: path
     *          name: stageId
     *          schema:
     *            type: string
     *          required: true
     *          description: stage id.
     *      responses:
     *        200:
     *          description: stage successfully retrieved.
     *          content:
     *            application/json:
     *              schema:
     *                type: object
     *                $ref: '#/components/schemas/Stage'
     *        404:
     *          description: stage not found.
     *        500:
     *          description: Error trying to get the stage.
     */
    .get(trips.read_a_stage)

    /**
     * @swagger
     * /v1/stages/{stageId}:
     *    put:
     *      summary: Update a stage.
     *      tags: [Stage]
     *      parameters:
     *        - in: path
     *          name: stageId
     *          schema:
     *            type: string
     *          required: true
     *          description: Stage id.
     *      requestBody:
     *        required: true
     *        content:
     *          application/json:
     *            schema:
     *              type: object
     *              $ref: '#/components/schemas/Stage'
     *      responses:
     *        200:
     *          description: Stage successfully updated.
     *          content:
     *            application/json:
     *              schema:
     *                type: object
     *                $ref: '#/components/schemas/Stage'
     *        403:
     *          description: You don't have right role to carry out this operation. Only a manager can update it.
     *        404:
     *          description: Stage not found.
     *        500:
     *          description: Error trying to update the stage.
     */
    .put(trips.update_a_stage)

    /**
     * @swagger
     * /v1/stages/{stageId}:
     *    delete:
     *      summary: Delete a stage.
     *      tags: [Stage]
     *      parameters:
     *        - in: path
     *          name: stageId
     *          schema:
     *            type: string
     *          required: true
     *          description: Stage id.
     *      responses:
     *        200:
     *          description: Stage successfully deleted.
     *          content:
     *            application/json:
     *              schema:
     *                type: object
     *                $ref: '#/components/schemas/Stage'
     *        403:
     *          description: You don't have right role to carry out this operation. Only a manager can delete it.
     *        404:
     *          description: Stage not found.
     *        500:
     *          description: Error trying to delete the stage.
     */
    .delete(trips.delete_a_stage);
};
